name: orders-payments-stack

services:
  # --------- APPS ---------
  orders-ms:
    build:
      context: https://github.com/llipiterdev/orders-ms.git#main
      dockerfile: Dockerfile
    container_name: orders-ms
    environment:
      # URL interna en la red de Docker (puerto expuesto por payments dentro del contenedor)
      PAYMENTS_URL: http://payments-ms:3000
    depends_on:
      - payments-ms
    ports:
      - "3002:3000"   # host:container (antes 3000:3000)
    networks:
      - backend

  payments-ms:
    build:
      context: https://github.com/llipiterdev/payments-ms.git#main
      dockerfile: Dockerfile
    container_name: payments-ms
    # healthcheck opcional si tu imagen trae curl o wget
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://localhost:3000/health || wget -qO- http://localhost:3000/health"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 10
    ports:
      - "3001:3000"   # host:container
    networks:
      - backend

  # --------- TESTS (activar con --profile test) ---------
  orders-tests:
    build:
      context: https://github.com/llipiterdev/orders-ms.git#main
      dockerfile: Dockerfile
      # Si tienes un stage con dev-deps, puedes usar:
      # target: builder
    profiles: ["test"]
    networks: [backend]
    depends_on:
      - payments-ms
    environment:
      PAYMENTS_URL: http://payments-ms:3000
    # Anula entrypoint de la imagen (evita que ejecute "node dist/main")
    entrypoint: ["/bin/sh","-lc"]
    command: >
      npm ci || true &&
      npm run test &&
      npm run test:e2e &&
      npx stryker run

  payments-tests:
    build:
      context: https://github.com/llipiterdev/payments-ms.git#main
      dockerfile: Dockerfile
      # target: builder
    profiles: ["test"]
    networks: [backend]
    entrypoint: ["/bin/sh","-lc"]
    command: >
      npm ci || true &&
      npm run test &&
      npm run test:e2e &&
      npx stryker run

networks:
  backend: {}