name: orders-payments-stack

services:
  # --------- APPS ---------
  orders-ms:
    image: orders-payments-stack_orders-ms
    build:
      context: https://github.com/llipiterdev/orders-ms.git#main
      dockerfile: Dockerfile
    container_name: orders-ms
    environment:
      PAYMENTS_URL: http://payments-ms:3000
    depends_on:
      - payments-ms
    ports:
      - "3002:3000"   # host:container (evita choque con 3000)
    networks:
      - backend

  payments-ms:
    image: orders-payments-stack_payments-ms
    build:
      context: https://github.com/llipiterdev/payments-ms.git#main
      dockerfile: Dockerfile
    container_name: payments-ms
    ports:
      - "3001:3000"
    networks:
      - backend

  # --------- TESTS (activar con --profile test) ---------
  orders-tests:
    build:
      context: https://github.com/llipiterdev/orders-ms.git#main
      dockerfile: Dockerfile
      target: builder                # usa el stage con dev-deps y fuente
    profiles: ["test"]
    networks: [backend]
    depends_on:
      - payments-ms
    environment:
      PAYMENTS_URL: http://payments-ms:3000
    working_dir: /app
    # Usa shell directamente (sin entrypoint propio)
    command: >
      /bin/sh -lc "
        npm test &&
        npm run test:e2e &&
        npx stryker run
      "

  payments-tests:
    build:
      context: https://github.com/llipiterdev/payments-ms.git#main
      dockerfile: Dockerfile
      target: builder
    profiles: ["test"]
    networks: [backend]
    working_dir: /app
    command: >
      /bin/sh -lc "
        npm test &&
        npm run test:e2e &&
        npx stryker run
      "

networks:
  backend: {}